### ISSUE TITLE
Add flickr redirect functionality.

### ISSUE THREAD

**Issue by jarred** [jarred/src-img#1]
So, if the image is hosted by flickr, track down and redirect to the photos page.

**Comment by GeekJosh** [comment]
Is there anyway to disable this "functionality"? The image I'm checking is on flickr, my flickr, I want to see if it's anywhere else not just get redirected back to my own page as I am doing now...

**Comment by jarred** [comment]
@LosOjos we could disable it if you click the bookmarklet on a flickr page? Otherwise (say if the image is on a blog) we will redirect to the flickr page.

@hydnhntr can you update your regex to do this?

**Comment by jarred** [comment]
This has been deployed. Grab this new version of the [bookmarklet](http://jarred.github.com/src-img/).

**Comment by GeekJosh** [comment]
Wow, super fast turn-around! Cheers!

**Comment by GeekJosh** [comment]
Unfortunately, it doesn't appear to work, I'm still getting redirected straight back to flickr

**Comment by jarred** [comment]
@LosOjos have you removed and re-added the bookmarklet? It is working for me.

**Comment by GeekJosh** [comment]
Yeah I did, still just keeps sending me back to the flickr page I searched
from... if it helps, I'm using Chrome 18.0.1025.142 (latest version)

On Tue, Apr 3, 2012 at 8:39 PM, Jarred Bishop <
reply@reply.github.com

**Comment by GeekJosh** [comment]
Seems to be working now, thanks! Don't know if you've updated it or not, perhaps Chrome was buffering it somehow? Anyway, it works, thanks you!
