### ISSUE TITLE
redirect to google homepage

### ISSUE THREAD

**Issue by kiban** [jarred/src-img#2]
Worked fine yesterday. But now everytime I click on an image I get redirected to a generic google search page.

**Comment by jarred** [comment]
A few people are having this issue, and I'm concerned it might actually be something happening at Googles end and out of my control.

Can you do me a favor? Can you right click on a src-img link and copy and paste the link here for me?

![Screenshot](http://f.cl.ly/items/022u423Q050i1J3O3c0l/Screen-Shot-2011-11-03-at-7.39.jpg)

Also, does it redirect to google.com or a localized version of google (like google.co.uk or google.co.nz)?

**Comment by natharward** [comment]
From this Wiki page, http://en.wikipedia.org/wiki/Charles_Taze_Russell

I get:
http://images.google.com/searchbyimage?image_url=http%3A//upload.wikimedia.org/wikipedia/commons/thumb/1/18/Charles_Taze_Russell_sharp.jpg/220px-Charles_Taze_Russell_sharp.jpg&image_content=&bih=281&biw=220

Lands at http://www.google.com

**Comment by jarred** [comment]
Thanks, if you just click that link above (the images.google.com one) does the same thing happen? Google are suggesting to clear you cache and cookies for a fix.

**Comment by natharward** [comment]
Worked in IE ... I'm always hesitant to clear my Firefox cache and cookies; lots of saved stuff, ya know?

What do you know about this working on iPhone? I tried bookmark, but it didn't load the ?? logo over the image.

**Comment by jarred** [comment]
Fair enough.

I haven't done any iOS testing, will add that to the features list.

**Comment by natharward** [comment]
cool man, that would be awesome. keep up the good stuff!
